/*Table structure for table `news` */

drop table if exists `news`;

CREATE TABLE `news` (
  `id` bigint(20) NOT NULL auto_increment,
  `title` varchar(255) NOT NULL default '',
  `annotation` text NOT NULL,
  `content` longtext NOT NULL,
  `date` date NOT NULL default '0000-00-00',
  PRIMARY KEY  (`id`),
  KEY `date` (`date`)
) TYPE=MyISAM;

/*Data for the table `news` */

INSERT INTO `news` VALUES (1, 'Happy New 2007 Year!!!', 'It''s 2007! Fill your heart with new hopes, reach out for new opportunities and celebrate the New Year! Cheers!', '<p>The previous 2006 year was really full of exciting events for the core dev.team:</p>\r\n<p>Firstly we finally <a href="http://limb-project.com/root/news/158">managed to launch</a> the <a href="http://pear.limb-project.com">Limb 3.x PEAR channel</a>. We have high hopes for Limb 3.x and all our future efforts will be mainly focused on further development and improvement of Limb 3.x packages. We''re pushing the PHP''s limits with Limb 3.x and prove that PHP still can be a powerfull RAD tool despite to much PHP criticizing lately.</p>\r\n<p>Secondly we released <a href="http://limb-project.com/root/news/159">Limb 2.4-rc1 stable release</a>(well, almost stable since it''s a release candidate) after more than one year of silence in this branch. We hope to release 2.4 final pretty soon and even though many developers still find 2.x attractive we''d like to admit that there won''t be much development in this branch in the future. The code base of 2.x is pretty outdated and sometimes ugly, that''s why we want to convert 2.x into 3.x package as soon as possible.</p>', '2007-01-01');
INSERT INTO `news` VALUES (2, 'LIMB 2.4-rc1 Release', 'Well, finally, here comes the first stable version of Limb 2.4.x with lots of bugfixes and some new cool features!', '<p>Here''s the list of the most noticeable changes:</p>\r\n\r\n<ul>\r\n<li>PHP-4.4.x compatibility(we really tried hard to spot all problematic places in the code)</li>\r\n<li>improved JavaScript bundling mechanism, which can be nicely combined with dynamic JavaScript loading of modules.</li>\r\n</ul>\r\n\r\n<p>See <a href="https://svn.limb-project.com/limb/2.x/tags/2.4-rc1/CHANGELOG">CHANGELOG</a> for more details. </p>\r\n\r\n<p>We hope 2.4 final release will follow soon after this one, once this release is a bit more tested with PHP-4.4.x on production servers. However we admit that we''re mainly focused on Limb 3.x development and after 2.4 final release most probably the 2.x branch will be closed.</p>', '2006-12-20');
INSERT INTO `news` VALUES (3, 'LIMB 3.x PEAR channel was officially launched!', 'After almost a year of hard working we''re proud to announce the launch of PEAR channel for Limb 3.x packages!', '<p>These packages should greatly simplify the process of developing web applications with PHP. One of the most interesting packages among them is <b>web_app</b> which allows you to develop web applications in <a href="http://rubyonrails.com">Rails</a> alike way using similar controllers, pretty flexible ActiveRecord powered model and excellent <a href="http://phpwact.org">WACT</a> based views.</p>\r\n\r\n<p>The channel has a bit terse look right now however this is going to be fixed pretty soon. We''re also working on providing automatic nightly builds of packages right from the repository.</p>\r\n\r\n<p>The english documentation is mostly outdated but we''re working on this issue as well(we''re finishing the Russian documentation at the moment). However there are some simple examples in <b>web_app</b> package which, hopefully, should help you get started quickly.</p>\r\n\r\n<p>We''d like to thank all core Limb developers for their great work and dedication to the project. It would never have happened without you guys!</p>\r\n\r\n<p>Let it be a new year present to all PHP agile geeks ;)</p>', '2006-12-15');
INSERT INTO `news` VALUES (4, 'Moving from Trac to JIRA', 'LIMB is gradually becoming a pretty large project and with the new conception of packages it has become pretty difficult to use Trac with many sub-projects.', '<p>Trac is a great tool for tracking issues for one project however it doesn''t allow to add new sub-projects easily and that''s become quite problematic. </p>\r\n\r\n<p><a href="http://www.atlassian.com/software/jira/">JIRA</a> is a another super flexible and configurable tool written in Java which allows you to have almost complete control over project issues. We decided to <a href="http://www.atlassian.com/software/views/opensource-license-request.jsp">apply</a> for JIRA Open Source free license and...<a href="http://www.atlassian.com/">atlassian</a> folks were very generous to provide us with the free copy of JIRA. Thank you so much!</p>\r\n\r\n<p>We installed JIRA at <a href="http://jira.limb-project.com">http://jira.limb-project.com</a>, made some minor look-and-feel changes and moved all unresolved issues from Trac there.</p>\r\n\r\n<p>We also made some projects in JIRA: a separate project for LIMB 2.x, a bunch of projects for LIMB 3.x packages(each package gets its own project) and one for all project related issues(site redesing, new mailing lists, etc)</p>\r\n\r\n<p>Trac link is not available anymore and it simply redirects to JIRA. Good buy, old pal.</p>', '2006-10-16');
INSERT INTO `news` VALUES (5, 'Two years of happy hacking.', 'This very day two years ago limb-project.com was launched and two days later the first release of LIMB was available for public download at SourceForge.net.', '<p>The core LIMB dev. team has had a lot of hard work and fun in the course of these two years and we''d like to thank our small(but constantly growing) community for helping us spotting bugs, sending patches and requesting insane features :)</p>', '2006-06-04');
