<?php $action_form = lmbToolkit :: instance()->getRoutesUrl(array('action'=>'sync'), '', false); ?>
{{form name='list_form' target="sync_popup" action="{$action_form}" method='post' onSubmit="var w = window.open('', this.target, 'toolbar=0,location=0,width=800px,height=800px,scrollbars=1'); w.focus(); return true;"}}
{{list using="$#item.projects" as="$project"}}
  <table id='list'>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Last Sync</th>
    <th>Last Rev</th>
    <th>Current Rev</th>
    <th>Info</th>
    <th>Actions</th>
  </tr>
  {{list:item}}
  <tr class='list'>
    <td class='selector'>{{input type='checkbox' name='ids[]' value='{$project.name}' class='input' /}}</td>
    <td class='project_name'>
      <a name="project_{$project->name}"></a>
      <?php $project_class = $project->is_changed ? 'changed' : 'not_changed'; ?>
      <span class="{$project_class}" onclick='info_toggle("{$project.name}_info"); return false;'>
          {$project->name}
      </span>
    </td>
    <td>{$project.last_sync_date}</td>
    <td>{$project.last_sync_rev}</td>
    <td>{$project.repository_rev}</td>
    <td width='50%'>
      <a href='#' id='{$project.name}_info_toggle' onclick='info_toggle("{$project.name}_info"); return false;'><img src="images/icon/plus.gif"  width='10' height='10' alt='plus'/></a>
      <dl id='{$project.name}_info' class='info'>
        <pre>
        {$project.exported_config}
        </pre>
      </dl>
    </td>
    <td class='actions'>
      <? if($project->is_locked) {?>
        <a href="{{route_url params='action:unlock,id:{$project.name}'}}"  onclick="res = confirm('Confirm action: unlock project \'{$project.name}\'.');if(res){w = window.open(this.href, 'Unlock', 'toolbar=0,location=0,width=400px,height=400px');w.focus();};return false"><img src="images/icon/unlock.gif" alt="Unlock" title="Force unlock"/></a>
      <? } else { ?>
        <a href="{{route_url params='action:sync'}}?id={$project.name}" onclick="res = confirm('Confirm action: synchronize project \'{$project.name}\' with remote.');if(res){w = window.open(this.href, 'Sync!', 'toolbar=0,location=0,width=800px,height=800px');w.focus();};return false"><img src="images/icon/sync.gif" alt="Sync!" title="Synchronize project with remote"/></a>
      <? } ?>
      <a href="{{route_url params='action:diff,id:{$project.name}'}}"  onclick="w = window.open(this.href, 'Diff', 'toolbar=0,location=0,width=800px,height=800px');w.focus();return false"><img src="images/icon/diff.gif" alt="Diff" title="Show difference"/></a>
      <? if($project->history) { ?>
        <a href="{{route_url params='action:rollback,id:{$project.name}'}}"><img src="images/icon/diff.gif" alt="rollback" title="Rollback"/></a>
      <? } ?>
    </td>
  </tr>
  {{/list:item}}
  </table>
  {{input type='submit' value='Sync!' /}}
{{/list}}  
{{/form}}

