<?php $action_form = lmbToolkit :: instance()->getRoutesUrl(array('action'=>'sync'), '', false); ?>

{{form name='list_form' target="sync_popup" action="{$action_form}" method='post' onSubmit="var w = window.open('', this.target, 'toolbar=0,location=0,width=800px,height=800px,scrollbars=1'); w.focus(); return true;"}}

  {{list using="$#item.projects" as="$project"}}
    <table id='list'>
      <tr>
        <th>Name</th>
        <th>Last Sync</th>
        <th>Rev</th>
        <th>Info</th>
        <th>Actions</th>
      </tr>
      {{list:item}}

      <?
        if(isset($project_detail[$project->name]) && $project_detail[$project->name] == 1)
          $show = 1;
        else
          $show = 0;
      ?>

      <tr class='list'>
        <td class='project_name'>
          <a name="project_{$project->name}"></a>
          <?php $project_class = $project->is_changed ? 'changed' : 'not_changed'; ?>
          <span class="{$project_class}" onclick='info_toggle("{$project.name}"); return false;'>
            {$project->name}
          </span>
        </td>
        <td>{$project.last_sync_date}</td>
        <td>{$project.last_sync_rev}</td>
        <td width='50%'>
          <a href='#' id='{$project.name}_info_toggle' onclick='info_toggle("{$project.name}"); return false;'><img <? if($show) { ?>src="images/icon/minus.gif"<? } else { ?>src="images/icon/plus.gif"<? } ?>  width='10' height='10' alt='plus'/></a>
          <dl id='{$project.name}_info' class='info' <? if($show) { ?>style="display:block;"<? } ?>>
          <pre>
  {$project.exported_config}
          </pre>
          </dl>
        </td>
        <td class='actions'>
          <? if($project->getRepository()->getType() == 'svn') { ?>
            <input type='checkbox' name='ignore_externals[]' class="ignore_externals_checkbox" value='{$project.name}' checked='checked' title='Ignore externals'/>
          <? } ?>

          <? if($project->is_locked) {?>
            <a href="{{route_url params='action:unlock,id:{$project.name}'}}"  onclick="return unlock.call(this, '{$project.name}');"><img src="images/icon/unlock.gif" alt="Unlock" title="Force unlock"/></a>
          <? } else {?>
            <a href="{{route_url params='action:sync'}}?id={$project.name}&ignore-externals=true" class="sync_link" onclick="return sync.call(this, '{$project.name}');"><img src="images/icon/sync.gif" alt="Sync!" title="Synchronize project with remote"/></a>
          <? } ?>

          <a href="{{route_url params='action:diff,id:{$project.name}'}}"  onclick="return diff.call(this);"><img src="images/icon/diff.gif" alt="Diff" title="Show difference"/></a>

          <a href="{{route_url params='action:log,id:{$project.name}'}}"  onclick="return log.call(this);"><img src="images/icon/log.gif" alt="Log" title="Show difference log"/></a>

          <? if($project->needHistory()) { ?>
            <a href="{{route_url params='action:rollback,id:{$project.name}'}}"><img src="images/icon/diff.gif" alt="rollback" title="Rollback"/></a>
          <? } ?>
        </td>
      </tr>
    {{/list:item}}
    </table>
  {{/list}}

{{/form}}

{{into slot="js_include"}}
  <script type="text/javascript">
    jQuery(document).ready(function(){
      jQuery('.ignore_externals_checkbox').bind('change',function(){
        var sync_link = jQuery(this).parents('.list').find('a.sync_link')[0];
        if( this.checked ){
          sync_link.href += '&ignore-externals=true';
        }else{
          sync_link.href = sync_link.href.replace('&ignore-externals=true', '');
        }
        
      })
    });

    function unlock(project_name){
      var res = confirm('Confirm action: unlock project \'' + project_name + '\'.');
      if(res){
        w = window.open(this.href, 'Unlock', 'toolbar=0,location=0,width=400px,height=400px');
        w.focus();
      };
      return false;
    }

    function sync(project_name){
      var res = confirm('Confirm action: synchronize project \'' + project_name + '\' with remote.');
      if(res){
        w = window.open(this.href, 'Sync!', 'toolbar=0,location=0,width=800px,height=800px');
        w.focus();
      };
      return false;
    }

    function diff(){
      var w = window.open(this.href, 'Diff', 'toolbar=0,location=0,width=800px,height=800px');
      w.focus();
      return false;
    }

    function log(){
      w = window.open(this.href, 'Log', 'toolbar=0,location=0,width=800px,height=800px');
      w.focus();
      return false;
    }
  </script>
{{/into}}