
{{form name='list_form' method='post'}}
{{list using="$#item.projects" as="$project"}}
  <table id='list'>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Last Sync</th>
    <th>Last Rev</th>
    <th>Current Rev</th>
    <th>Info</th>
    <th>Actions</th>
  </tr>
  {{list:item}}
  <tr class='list'>
    <td class='selector'>{{input type='checkbox' name='ids[]' value='{$project.name}' class='input' /}}</td>
    <td class='project_name'>
      <?php $project_class = $project->is_changed ? 'changed' : 'not_changed'; ?>
      <span class="{$project_class}" onclick='info_toggle("{$project.name}_info"); return false;'>
          {$project->name}
      </span>
    </td>
    <td>{$project.last_sync_date}</td>
    <td>{$project.last_sync_rev}</td>
    <td>{$project.repository_rev}</td>
    <td width='50%'>
      <a href='#' id='{$project.name}_info_toggle' onclick='info_toggle("{$project.name}_info"); return false;'><img src="/images/icon/plus.gif"  width='10' height='10' alt='plus'/></a>
      <dl id='{$project.name}_info' class='info'>
        <dt>Repos:</dt><dd>{$project.repository}</dd>
        <dt>Remote host:</dt><dd>{$project.user}@{$project.host}</dd>
        <dt>Remote dir:</dt><dd>{$project.remote_dir}</dd>
        <dt>Presync cmd:</dt><dd>{$project.presync_cmd}</dd>
        <dt>Sync cmd:</dt><dd>{$project.sync_cmd}</dd>
        <dt>Postsync cmd:</dt><dd>{$project.postsync_cmd}</dd>
        <?php if (isset($project->url)) { ?>
          <dt>Project URI:</dt><dd><a href="{$project.url}" class='project' target="_blank">{$project.url}</a></dd>
        <?php } ?>

      </dl>
    </td>
    <td class='actions'>
      <?php if($project->is_locked) {?>
        <a href="{{route_url params='action:unlock,id:{$project.name}'}}"  onclick="res = confirm('Confirm action: unlock project \'{$project.name}\'.');if(res){w = window.open(this.href, 'Unlock', 'toolbar=0,location=0,width=400px,height=400px');w.focus();};return false"><img src="/images/icon/unlock.gif" alt="Unlock" title="Force unlock"/></a>
      <?php } else { ?>
        <a href="{{route_url params='action:sync'}}?id={$project.name}" onclick="res = confirm('Confirm action: synchronize project \'{$project.name}\' with remote.');if(res){w = window.open(this.href, 'Sync!', 'toolbar=0,location=0,width=800px,height=800px');w.focus();};return false"><img src="/images/icon/sync.gif" alt="Sync!" title="Synchronize project with remote"/></a>
      <?php } ?>
      <a href="{{route_url params='action:diff,id:{$project.name}'}}"  onclick="w = window.open(this.href, 'Diff', 'toolbar=0,location=0,width=800px,height=800px');w.focus();return false"><img src="/images/icon/diff.gif" alt="Diff" title="Show difference"/></a>
    </td>
  </tr>
  {{/list:item}}
  </table>
  <?php $url_js = lmbToolkit :: instance()->getRoutesUrl(array('action'=>'sync'), '', false); ?>
  {{input type='submit' value='Sync!' onclick='Limb.Form.submit(this.form, "{$url_js}?popup=1"); return false;'/}}
{{/list}}  
{{/form}}

