<html>
<head>
  <title>Syncman projects</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <base href="<?php echo LIMB_HTTP_BASE_PATH; ?>"/>
  <link rel="stylesheet" href="styles/main.css" type="text/css" />
</head>
<body id='popup'>

  <div id="wrapper">

    <div id="head">
      <img src="images/logo.syncman.small.gif"  width='159' height='40' alt='SYNCMAN' id='logo'/>
    </div>
    
    <fieldset>
       <legend>Getting diff...</legend>
       <iframe width='100%' height='100%' src='projects/perform_diff/{$#request.id}'></iframe>
    </fieldset>
    
  </div>

</body>
</html>
