<? $this->title = 'Projects' ?>
{{insert file="page.phtml"}}
  {{insert:into slot='head'}}
<script src="js/prototype.js"></script>
<script src="js/jquery.js"></script>
<script src="js/jquery.cookie.js"></script>
<script src="js/main.js"></script>
<script src="js/getDetailForCategory.js"></script>
  {{/insert:into}}
  {{insert:into slot='content'}}
      {{list:list using="$#category" as="$item"}}
      {{list:item}}

      <?php if(isset($this->category_detail[$item->name]) && $this->category_detail[$item->name] == 1)  
              $open = 1;
            else
              $open = 0;
      ?>
       <fieldset>
         <legend>
         <?php $state = $open == 0 ? 'open' : 'close'; ?>
         <a href="{{route_url params='action:detail'}}?category={$item.name}"
            id='{$item.name}_category_toggle' 
            onclick="getDetailForCategory('{$item.name}_category'); return false;"
            class="category">
         <strong>Category '{$item.name}'</strong>
         <img src="images/icon/{$state}.gif"  width='11' height='11' alt='{$state}'/>
         </a>
         </legend>

         <div id='{$item.name}_category'>
         <?php if($open == 1) { ?>
          <?php $this->item = $item; ?>
          {{include file='projects/detail.phtml' project_detail="{$#project_detail}"/}}
         <?php } ?>
         </div>

        </fieldset>

      {{/list:item}}
      {{/list:list}}
  {{/insert:into}}
{{/insert}}