<html>
<head>
  <title>Syncman projects</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <base href="<?php echo LIMB_HTTP_BASE_PATH; ?>"/>
  <link rel="stylesheet" href="styles/main.css" type="text/css" />
</head>
<body id='popup'>

  <div id="wrapper">

    <div id="head">
      <img src="images/logo.syncman.small.gif"  width='159' height='40' alt='SYNCMAN' id='logo'/>
    </div>
  
    <fieldset>
       <legend>Synchronization...</legend>
        <?php
          if(isset($_REQUEST['id']))
            $id = 'id='.urlencode($_REQUEST['id']);
          elseif(isset($_REQUEST['ids']))  
          {
            $id = 'ids[]='.implode('ids[]=', array_map('urlencode', $_REQUEST['ids']));
          }
          
          $ignore_externals = (bool)@$_REQUEST['ignore-externals'];
          $ignore_externals = $ignore_externals ? '&ignore-externals=true' : ''; 
          
          echo "<iframe width='100%' height='70px' src='".LIMB_HTTP_BASE_PATH."projects/start_sync?{$id}{$ignore_externals}'></iframe>";
        ?>
    </fieldset>
  
  </div>
</body>
</html>
