<html>
<head>
  <title>Syncman projects</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <link rel="stylesheet" href="/styles/main.css" type="text/css" />
</head>
<body id='popup'>

  <div id="wrapper">

    <div id="head">
      <img src="/images/logo.syncman.small.gif"  width='159' height='40' alt='SYNCMAN' id='logo'/>
    </div>
  
    <fieldset>
       <legend>Synchronization...</legend>
        <?php
          if(isset($_REQUEST['id']))
            echo "<iframe width='100%' height='95%' src='/projects/start_sync/{$_REQUEST['id']}'></iframe>";
          elseif(isset($_REQUEST['ids']))  
            echo "<iframe width='100%' height='95%' src='/projects/start_sync?ids[]=" . implode('&ids[]=', $_REQUEST['ids']) . "'></iframe>";
        ?>
    </fieldset>
  
  </div>

</body>
</html>
