<html>
<head>
  <title>Syncman projects</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <link rel="stylesheet" href="/styles/main.css" type="text/css" />
</head>
<body id='popup'>

  <div id="wrapper">

    <div id="head">
      <img src="/images/logo.syncman.small.gif"  width='159' height='40' alt='SYNCMAN' id='logo'/>
    </div>
  
    <fieldset>
       <legend>Unlock...</legend>
       <div class="content">
          <input type="button" value='OK' onclick='window.opener.location.reload();window.close();' style='margin:10px;'/>
       </div> 
    </fieldset>
  
  </div>


  
</body>
</html>
